### ISSUE TITLE
Create Overlay (ST_Overlaps)

### ISSUE THREAD

**Issue by laurencjay** [developmentseed/zambia-buildings-import#2]
Includes two steps:
1. Translation of the Zambia-extract.geonjson into a Postgresql file and then 2. Overlaying the households dataset with the extract to figure out if there are redundancies that do not need to be included in the import.

**Comment by laurencjay** [comment]
After creating the Zambia extract and cleaning the duplicates from the Akros housing dataset, we conducting the following:
1. Converted the files to postgresql using ogr2ogr
2. Using PGAdmin and postgis, loaded the files into postgresql
3. Created spatial indexes on both of the files
4. Ran the ST_Overlaps query:

``` sql
Select ogrgeojson.ogc_fid, ogrgeojson.wkb_geometry
 From ogrgeojson, zambiaextract
 Where ST_Overlaps(ogrgeojson.wkb_geometry, zambiaextract.wkb_geometry)
```

This returned no results, meaning that there are no duplicates between OSM and the file we are importing. 
5. We confirmed our finding from postgis by using the Intersect tool in QGIS.

**Comment by smit1678** [comment]
@laurencjay Reopening this since our #9 showed some overlaps with OSM. A quick check in QGIS showed that there are 722 intersections with existing OSM data. While some of that is due to low-resolution OSM data, see screenshot below, we should remove these overlaps prior to upload. We can then set up a day sprint to go through the 722 errors and add them manually. 

Can you post the final dataset with intersecting buildings removed? 

![](https://api.monosnap.com/rpc/file/download?id=xnEtgQwl52VAGsVizkEI2v9UZh4yCj)

**Comment by laurencjay** [comment]
Uploaded a new version of the dataset HouseCleanUpdated.geojson.zip that removes all the buildings that overlap with existing OSM data. The houses that interact with OSM data will be edited and uploaded at a later date.

**Comment by laurencjay** [comment]
Remove the uploaded HouseCleanUpdated.geojson.zip. There has been a file added to the Repo called Upload files. These files have all undergone the following process:
1. Initial duplicates removed (internal duplicates within the dataset itself, these buildings will be uploaded at a later date)
2. Overlaid with the Zambia extract to remove all overlaps with OSM data
3. Clipped based on Zambia's provincial boundaries to create smaller upload files
4. Translated to a .osm file 
5. Run the validator in JOSM to remove other errors within the data (dangling ways)
